---

# file: deploy-kube-node-problem-detector-daemonset.yml
#

# func:
#   . create cluster addon file - node-problem-detector-daemonset addon


####################################################
#

#- name: create cluster addon directory
#  file:
#    path: "{{ kube_node_problem_detector_path }}/"
#    state: directory
#    owner: "{{ kube_user }}"
#    group: "{{ kube_group }}"
#    mode: 0644

- name: create cluster addon - node-problem-detect daemonset file
  template:
    src: "node-problem-detector/{{ item }}.j2" 
    dest: "{{ kube_node_problem_detector_path }}/{{ item }}"
    owner: "{{ kube_user }}"
    group: "{{ kube_group }}"
    mode: 0644
  with_items:
    - node-problem-detector.yaml
    - node-problem-detector-config.yaml

- name: create node-problem-detector daemonset and config
  command: "{{ bin_path }}/kubectl create -f {{ kube_node_problem_detector_path }}/node-problem-detector.yaml"
  run_once: true
  delegate_to: "{{ groups['kube-masters'][0] }}"

- name: create node-problem-detector daemonset and config
  command: "{{ bin_path }}/kubectl create -f {{ kube_node_problem_detector_path }}/node-problem-detector-config.yaml"
  run_once: true
  delegate_to: "{{ groups['kube-masters'][0] }}"

- name:
  debug:
    msg: "Finished. node-problem-detector addon daemonset and its config are deployed on cluster."

