---

# file: metrics-server-default-setting.yml


### PERFORMANCE AND SCALE
#
base_metrics_server_cpu: 80m
base_metrics_server_memory: 80Mi
metrics_server_memory_per_node: 8Mi

metrics_server_min_cluster_size: 1

# metrics server metric resolution (in seconds, default: 60s)
# metrics server flag: --metric_resolution
metrics_server_metric_resolution: 1m0s


### NETWORK ADDRESS AND PORT
#
# metrics server secure port - default port 443. use port other than default port (443) if not as root user
# metrics server flag: --secure-port 
# (we will use cluster-IP and nodePort - 30000 )
#metrics_server_secure_port: 30000
# use host network and port, before fix master networking to cluster ip
#metrics_server_secure_port: 443
metrics_server_secure_port: 4443


### KUBELET PORT
#
# metrics server will connect to metric port of kubelet (default secure port 10250 for kubelet)
# metrics server flag: --kubelet-port
metrics_server_kubelet_port: "{{ kubelet_secure_port }}"


### CA (CERTIFICATION AUTHORITY) FOR CLIENT CERTIFICATE
#
# metrics server client CA file
# metrics server flag: --requestheader-client-ca-file
metrics_server_client_ca_file: "{{ kube_ca_file }}"

### SERVER CERT OF METRICS-SERVER
# . CERT 
# metrics server server tls cert file
# metrics server flag: --tls-cert-file
metrics_server_tls_cert_file: "{{ kube_metrics_server_cert_file }}"
# . KEY
# metrics server server tls private key file
# metrics server flag: --tls-private-key-file
metrics_server_tls_private_key_file: "{{ kube_metrics_server_key_file }}"

### ALLOWED CLIENT USER NAME AND HEAD DATA FOR APISERVER AS PROXY TO ACCESS METRICS-SERVER
#
# metrics server requestheader-allowed-names (list)
# metrics server flag: --requestheader-allowed-names
# remark: defined same as CN user name defined in aggregated apiserver client cert (csr)
#         ie., "kube-aggregated-apiserver-client"
#

### CLIENT CERT (KUBECONFIG FILE) FOR METRICS-SERVER (AS CLIENT) TO ACCEESS APISERVER AND KUBELET SERVER
# flag: --authentication-kubeconfig   
# (use /etc/kubernetes/kubelet.kubeconfig)
metrics_server_authentication_kubeconfig_file: "{{ kubelet_config_file }}"

### CLIENT IDENTIFICATE (KUBECONFIG FILE) FOR METRICS-SERVER (AS CLIENT) TO ACCESS APISERVER AND KUBELET SERVER
# (authorized rights are allocated by using rbac )
# (use /etc/kubernetes/kubelet.kubeconfig)
# flag: --authorization-kubeconfig
metrics_server_authorization_kubeconfig_file: "{{ kubelet_config_file }}"


# METRICS-SERVER DEPLOY FILE DIRECTORY
#
metrics_server_yaml_path: "{{ kube_config_path }}/metrics-server"

