---

# file: create-default-iptables-file-worker-node.yml

#
- name:
  template:
#    src: ../../cluster-defaults/templates/iptables-master-node-conf.j2
    src: ../../cluster-defaults/templates/iptables-direct-master-node-conf.j2
    dest: /etc/sysconfig/iptables-master-node.backup
- name:
  template:
#    src: ../../cluster-defaults/templates/iptables-worker-node-conf.j2
    src: ../../cluster-defaults/templates/iptables-direct-worker-node-conf.j2
    dest: /etc/sysconfig/iptables-worker-node.backup

- name:
  template:
#    src: ../../cluster-defaults/templates/iptables-worker-node-conf.j2
    src: ../../cluster-defaults/templates/iptables-direct-worker-node-conf.j2
    dest: /etc/sysconfig/iptables
